/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.IMPRIMIR;
import clases.control;
import clases.validar;
import java.awt.event.KeyEvent;
import java.util.HashMap;
import java.util.Objects;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class alumno extends javax.swing.JDialog {

         /**
          * Creates new form alumno
          */
         public alumno(java.awt.Frame parent, boolean modal) {

                  super(parent, modal);

                  initComponents();
                  setTitle("alunmos");
                  control.fillTable2(tabla, " select * from v_alumnos");
                  control.fillCombo(cb_escuela, "select nomesc from escuela");
                  setLocationRelativeTo(null);
         }

         /**
          * This method is called from within the constructor to
          * initialize the form. WARNING: Do NOT modify this code. The
          * content of this method is always regenerated by the Form
          * Editor.
          */
         @SuppressWarnings("unchecked")
         // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
         private void initComponents() {

                  jPanel1 = new javax.swing.JPanel();
                  jLabel1 = new javax.swing.JLabel();
                  jLabel2 = new javax.swing.JLabel();
                  jLabel3 = new javax.swing.JLabel();
                  jLabel4 = new javax.swing.JLabel();
                  jSeparator1 = new javax.swing.JSeparator();
                  jLabel5 = new javax.swing.JLabel();
                  jLabel6 = new javax.swing.JLabel();
                  jLabel7 = new javax.swing.JLabel();
                  jLabel8 = new javax.swing.JLabel();
                  txt_nom = new javax.swing.JTextField();
                  txt_apell = new javax.swing.JTextField();
                  txt_dni = new javax.swing.JTextField();
                  txt_cod = new javax.swing.JTextField();
                  cb_gen = new javax.swing.JComboBox<>();
                  txt_dir = new javax.swing.JTextField();
                  txt_celular = new javax.swing.JTextField();
                  txt_correo = new javax.swing.JTextField();
                  jLabel10 = new javax.swing.JLabel();
                  cb_escuela = new javax.swing.JComboBox<>();
                  jPanel2 = new javax.swing.JPanel();
                  jScrollPane1 = new javax.swing.JScrollPane();
                  tabla = new javax.swing.JTable();
                  jLabel9 = new javax.swing.JLabel();
                  txt_buscar = new javax.swing.JTextField();
                  jButton1 = new javax.swing.JButton();
                  btn_salir = new javax.swing.JButton();
                  btn_cancelar = new javax.swing.JButton();
                  btn_eliminar = new javax.swing.JButton();
                  btn_actualizar = new javax.swing.JButton();
                  btn_crear = new javax.swing.JButton();

                  setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                  jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("datos de los alumos vulnerables"));

                  jLabel1.setText("nombre");

                  jLabel2.setText("apellido");

                  jLabel3.setText("dni");

                  jLabel4.setText("codigo");

                  jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

                  jLabel5.setText("direccion");

                  jLabel6.setText("correo");

                  jLabel7.setText("celular");

                  jLabel8.setText("genero");

                  txt_nom.setName("nombre"); // NOI18N
                  txt_nom.addKeyListener(new java.awt.event.KeyAdapter() {
                           public void keyTyped(java.awt.event.KeyEvent evt) {
                                    txt_nomKeyTyped(evt);
                           }
                  });

                  txt_apell.setName("apellido"); // NOI18N
                  txt_apell.addKeyListener(new java.awt.event.KeyAdapter() {
                           public void keyTyped(java.awt.event.KeyEvent evt) {
                                    txt_apellKeyTyped(evt);
                           }
                  });

                  txt_dni.setName("dni"); // NOI18N
                  txt_dni.addKeyListener(new java.awt.event.KeyAdapter() {
                           public void keyPressed(java.awt.event.KeyEvent evt) {
                                    txt_dniKeyPressed(evt);
                           }
                           public void keyTyped(java.awt.event.KeyEvent evt) {
                                    txt_dniKeyTyped(evt);
                           }
                  });

                  txt_cod.setName("codigo"); // NOI18N
                  txt_cod.addKeyListener(new java.awt.event.KeyAdapter() {
                           public void keyTyped(java.awt.event.KeyEvent evt) {
                                    txt_codKeyTyped(evt);
                           }
                  });

                  cb_gen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
                  cb_gen.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    cb_genActionPerformed(evt);
                           }
                  });

                  txt_dir.setName("direccion"); // NOI18N

                  txt_celular.setName("celular"); // NOI18N
                  txt_celular.addKeyListener(new java.awt.event.KeyAdapter() {
                           public void keyTyped(java.awt.event.KeyEvent evt) {
                                    txt_celularKeyTyped(evt);
                           }
                  });

                  txt_correo.setName("correo"); // NOI18N

                  jLabel10.setText("escuela");

                  cb_escuela.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

                  javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                  jPanel1.setLayout(jPanel1Layout);
                  jPanel1Layout.setHorizontalGroup(
                           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(34, 34, 34)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                             .addGroup(jPanel1Layout.createSequentialGroup()
                                                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                               .addComponent(jLabel3)
                                                               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                                               .addComponent(jLabel4))
                                                      .addGap(18, 18, 18)
                                                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                               .addComponent(txt_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                               .addComponent(txt_apell, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                               .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                               .addComponent(txt_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                             .addGroup(jPanel1Layout.createSequentialGroup()
                                                      .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addGap(18, 18, 18)
                                                      .addComponent(cb_escuela, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(53, 53, 53)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addComponent(jLabel5)
                                             .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                             .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                             .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addComponent(txt_celular, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addComponent(txt_dir, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addComponent(cb_gen, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(30, 30, 30))
                  );
                  jPanel1Layout.setVerticalGroup(
                           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                             .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addComponent(jLabel1))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                             .addComponent(jLabel2)
                                             .addComponent(txt_apell, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                             .addComponent(txt_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addComponent(jLabel3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                             .addComponent(txt_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addComponent(jLabel4))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                             .addComponent(jLabel10)
                                             .addComponent(cb_escuela, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE))
                           .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addGroup(jPanel1Layout.createSequentialGroup()
                                                      .addGap(15, 15, 15)
                                                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                               .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                 .addComponent(jLabel8)
                                                                                 .addComponent(cb_gen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(txt_dir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(6, 6, 6))
                                                               .addComponent(jLabel5))
                                                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                      .addComponent(txt_celular, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addGap(0, 0, Short.MAX_VALUE))
                                             .addGroup(jPanel1Layout.createSequentialGroup()
                                                      .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                      .addComponent(jLabel7)))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addComponent(jLabel6))
                                    .addGap(38, 38, 38))
                           .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                  );

                  tabla.setModel(new javax.swing.table.DefaultTableModel(
                           new Object [][] {
                                    {null, null, null, null},
                                    {null, null, null, null},
                                    {null, null, null, null},
                                    {null, null, null, null}
                           },
                           new String [] {
                                    "Title 1", "Title 2", "Title 3", "Title 4"
                           }
                  ));
                  tabla.addMouseListener(new java.awt.event.MouseAdapter() {
                           public void mousePressed(java.awt.event.MouseEvent evt) {
                                    tablaMousePressed(evt);
                           }
                  });
                  jScrollPane1.setViewportView(tabla);

                  jLabel9.setText("buscar");

                  txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
                           public void keyTyped(java.awt.event.KeyEvent evt) {
                                    txt_buscarKeyTyped(evt);
                           }
                  });

                  jButton1.setText("reporte");
                  jButton1.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    jButton1ActionPerformed(evt);
                           }
                  });

                  javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                  jPanel2.setLayout(jPanel2Layout);
                  jPanel2Layout.setHorizontalGroup(
                           jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addGroup(jPanel2Layout.createSequentialGroup()
                                                      .addComponent(jLabel9)
                                                      .addGap(29, 29, 29)
                                                      .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 907, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                      .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addGap(0, 0, Short.MAX_VALUE))
                                             .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                      .addGap(0, 0, Short.MAX_VALUE)
                                                      .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1043, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addContainerGap())
                  );
                  jPanel2Layout.setVerticalGroup(
                           jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                             .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addComponent(jLabel9)
                                             .addComponent(jButton1))
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(56, 56, 56))
                  );

                  btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hogar.png"))); // NOI18N
                  btn_salir.setText("finalizar");
                  btn_salir.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    btn_salirActionPerformed(evt);
                           }
                  });

                  btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incorrecto.png"))); // NOI18N
                  btn_cancelar.setText("cancelar");
                  btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    btn_cancelarActionPerformed(evt);
                           }
                  });

                  btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar2.png"))); // NOI18N
                  btn_eliminar.setText("eliminar");
                  btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    btn_eliminarActionPerformed(evt);
                           }
                  });

                  btn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/libro.png"))); // NOI18N
                  btn_actualizar.setText("actualizar");
                  btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    btn_actualizarActionPerformed(evt);
                           }
                  });

                  btn_crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/añadir.png"))); // NOI18N
                  btn_crear.setText("crear");
                  btn_crear.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    btn_crearActionPerformed(evt);
                           }
                  });

                  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                  getContentPane().setLayout(layout);
                  layout.setHorizontalGroup(
                           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_crear, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_eliminar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(64, 64, 64))
                           .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addContainerGap(14, Short.MAX_VALUE))
                  );
                  layout.setVerticalGroup(
                           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(layout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                             .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addComponent(btn_cancelar)
                                             .addComponent(btn_eliminar)
                                             .addComponent(btn_actualizar)
                                             .addComponent(btn_crear))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(13, 13, 13))
                  );

                  pack();
         }// </editor-fold>//GEN-END:initComponents

         private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
                  // TODO add your handling code here:

                  if (tabla.getSelectedRowCount() != 0) {
                           if (!validar.esCajaVacio(txt_apell, txt_cod, txt_dni, txt_nom)) {
                                    if (cb_escuela.getSelectedIndex() != -1) {
                                             if (txt_dni.getText().trim().length() == 8) {
                                                      if (txt_correo.getText().trim().length() == 0 || validar.esCorreo(txt_correo.getText().trim())) {

                                                               if (JOptionPane.showConfirmDialog(btn_actualizar, "¿desea actualizar el alumno "
                                                                       + tabla.getValueAt(tabla.getSelectedRow(), 2) + "  " + tabla.getValueAt(tabla.getSelectedRow(), 3) + "?") == 0) {
                                                                        // ------------instruccion para actualizar ---------------------------------------------------
                                                                        int alumno_id = Integer.parseInt(tabla.getValueAt(tabla.getSelectedRow(), 0).toString());

                                                                        String nom = txt_nom.getText().trim();
                                                                        String apell = txt_apell.getText().trim();
                                                                        String dni = txt_dni.getText().trim();
                                                                        String cod = txt_cod.getText().trim();
                                                                        String direc = txt_dir.getText().trim();
                                                                        String cel = txt_celular.getText().trim();
                                                                        String email = txt_correo.getText().trim();
                                                                        String gen = cb_gen.getSelectedItem().toString();
                                                                        String esc = cb_escuela.getSelectedItem().toString();

                                                                        if (direc.length() == 0) {
                                                                                 direc = "sin Direccion";
                                                                        }

                                                                        if (cel.length() == 0) {
                                                                                 cel = "Sin Celular";
                                                                        }

                                                                        if (email.length() == 0) {
                                                                                 email = "sin Email";
                                                                        }

                                                                        String sql = String.format("call actualizar_alumnos(%s,'%s','%s','%s','%s','%s','%s','%s','%s','%s')", alumno_id, dni, nom, apell, gen, direc, cel, email, cod, esc);
                                                                        System.out.println(sql);
                                                                        if (control.update(sql) != 0) {
                                                                                 control.fillTable2(tabla, " select * from v_alumnos");
                                                                                 JOptionPane.showMessageDialog(btn_actualizar, "se actualizó con éxito");
                                                                        }

                                                                        //--------------------------------------------------------------------------------------------
                                                               }

                                                      } else {
                                                               JOptionPane.showMessageDialog(btn_actualizar, "el correo no es valido", "alerta", JOptionPane.WARNING_MESSAGE);
                                                      }

                                             } else {
                                                      JOptionPane.showMessageDialog(btn_actualizar, "el dni no puede ser menos de 8 dijitos", "alerta", JOptionPane.WARNING_MESSAGE);
                                             }

                                    } else {
                                             JOptionPane.showMessageDialog(btn_actualizar, "seleccione la escuela", "alerta", JOptionPane.WARNING_MESSAGE);
                                    }
                           }
                  } else {
                           JOptionPane.showMessageDialog(btn_actualizar, "seleccione una fila de la tabla", "alerta", JOptionPane.WARNING_MESSAGE);
                  }

         }//GEN-LAST:event_btn_actualizarActionPerformed

         private void cb_genActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_genActionPerformed
                  // TODO add your handling code here:
         }//GEN-LAST:event_cb_genActionPerformed

         private void btn_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearActionPerformed
                  // TODO add your handling code here:

                  if (!validar.esCajaVacio(txt_apell, txt_cod, txt_dni, txt_nom)) {
                           if (cb_escuela.getSelectedIndex() != -1) {
                                    if (txt_dni.getText().trim().length() == 8) {
                                             if (txt_correo.getText().trim().length() == 0 || validar.esCorreo(txt_correo.getText().trim())) {
                                                      String nom = txt_nom.getText().trim();
                                                      String apell = txt_apell.getText().trim();
                                                      String dni = txt_dni.getText().trim();
                                                      String cod = txt_cod.getText().trim();
                                                      String direc = txt_dir.getText().trim();
                                                      String cel = txt_celular.getText().trim();
                                                      String email = txt_correo.getText().trim();
                                                      String gen = cb_gen.getSelectedItem().toString();
                                                      String esc = cb_escuela.getSelectedItem().toString();

                                                      if (direc.length() == 0) {
                                                               direc = "sin Direccion";
                                                      }

                                                      if (cel.length() == 0) {
                                                               cel = "Sin Celular";
                                                      }

                                                      if (email.length() == 0) {
                                                               email = "sin Email";
                                                      }

                                                      String sql = String.format("call insertar_alumnos('%s','%s','%s','%s','%s','%s','%s','%s','%s')", dni, nom, apell, gen, direc, cel, email, cod, esc);
                                                      System.out.println(sql);
                                                      if (control.update(sql) != 0) {
                                                               control.fillTable2(tabla, " select * from v_alumnos");
                                                               JOptionPane.showMessageDialog(btn_crear, "se ingreso correctamente");
                                                      }

                                             } else {
                                                      JOptionPane.showMessageDialog(btn_crear, "el correo no es valido", "alerta", JOptionPane.WARNING_MESSAGE);
                                             }

                                    } else {
                                             JOptionPane.showMessageDialog(btn_crear, "el dni no puede ser menos de 8 dijitos", "alerta", JOptionPane.WARNING_MESSAGE);
                                    }

                           } else {
                                    JOptionPane.showMessageDialog(btn_crear, "seleccione la escuela", "alerta", JOptionPane.WARNING_MESSAGE);
                           }

                  }
         }//GEN-LAST:event_btn_crearActionPerformed

         private void txt_nomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nomKeyTyped
                  // TODO add your handling code here:
                  validar.SoloLetras(evt);
         }//GEN-LAST:event_txt_nomKeyTyped

         private void txt_apellKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apellKeyTyped
                  // TODO add your handling code here:
                  validar.SoloLetras(evt);
         }//GEN-LAST:event_txt_apellKeyTyped

         private void txt_dniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dniKeyTyped
                  // TODO add your handling code here:
                  if ((evt.getKeyChar() < 48) || (evt.getKeyChar() > 57) || txt_dni.getText().trim().length() > 7) {

                           evt.consume();

                  }

         }//GEN-LAST:event_txt_dniKeyTyped

         private void txt_codKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codKeyTyped
                  // TODO add your handling code here:

         }//GEN-LAST:event_txt_codKeyTyped

         private void txt_celularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_celularKeyTyped
                  // TODO add your handling code here:
                  validar.Solonumeros(evt);
         }//GEN-LAST:event_txt_celularKeyTyped

         private void txt_dniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dniKeyPressed
                  // TODO add your handling code here:

         }//GEN-LAST:event_txt_dniKeyPressed

         private void tablaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMousePressed
                  // TODO add your handling code here:
                  txt_dni.setText(tabla.getValueAt(tabla.getSelectedRow(), 1).toString());
                  txt_nom.setText(tabla.getValueAt(tabla.getSelectedRow(), 2).toString());
                  txt_apell.setText(tabla.getValueAt(tabla.getSelectedRow(), 3).toString());
                  cb_gen.setSelectedItem(tabla.getValueAt(tabla.getSelectedRow(), 4).toString());
                  if (!tabla.getValueAt(tabla.getSelectedRow(), 5).toString().equalsIgnoreCase("sin direccion")) {
                           txt_dir.setText(tabla.getValueAt(tabla.getSelectedRow(), 5).toString());
                  } else {
                           txt_dir.setText("");
                  }
                  if (!tabla.getValueAt(tabla.getSelectedRow(), 6).toString().equalsIgnoreCase("sin celular")) {
                           txt_celular.setText(tabla.getValueAt(tabla.getSelectedRow(), 6).toString());
                  } else {
                           txt_celular.setText("");
                  }
                  if (!tabla.getValueAt(tabla.getSelectedRow(), 7).toString().equalsIgnoreCase("sin Email")) {
                           txt_correo.setText(tabla.getValueAt(tabla.getSelectedRow(), 7).toString());
                  } else {
                           txt_correo.setText("");
                  }

                  txt_cod.setText(tabla.getValueAt(tabla.getSelectedRow(), 8).toString());
                  cb_escuela.setSelectedItem(tabla.getValueAt(tabla.getSelectedRow(), 9).toString());
         }//GEN-LAST:event_tablaMousePressed

         private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
                  // TODO add your handling code here:

                  if (tabla.getSelectedRowCount() != 0) {
                           if (JOptionPane.showConfirmDialog(btn_eliminar, "¿desea eliminar el alumno "
                                   + tabla.getValueAt(tabla.getSelectedRow(), 2) + "  " + tabla.getValueAt(tabla.getSelectedRow(), 3) + "?") == 0) {

                                    int alumno_id = Integer.parseInt(tabla.getValueAt(tabla.getSelectedRow(), 0).toString());

                                    String sql = String.format("call eliminar_alumnos(%s)", alumno_id);

                                    if (control.update(sql) != 0) {
                                             control.fillTable2(tabla, " select * from v_alumnos");
                                             JOptionPane.showMessageDialog(btn_eliminar, "se eliminó correctamente");

                                    }

                           }
                  } else {
                           JOptionPane.showMessageDialog(btn_eliminar, "seleccione la fila que deseas eliminar", "alerta", JOptionPane.WARNING_MESSAGE);
                  }


         }//GEN-LAST:event_btn_eliminarActionPerformed

         private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
                  // TODO add your handling code here:
                  txt_dni.setText("");
                  txt_nom.setText("");
                  txt_apell.setText("");
                  txt_dir.setText("");
                  txt_celular.setText("");
                  txt_correo.setText("");
                  txt_cod.setText("");
                  cb_escuela.setSelectedIndex(-1);
         }//GEN-LAST:event_btn_cancelarActionPerformed

         private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
                  // TODO add your handling code here:
                  if (JOptionPane.showConfirmDialog(btn_salir, "¿desea volver a la ventana  principal?") == 0) {
                           dispose();
                  }
         }//GEN-LAST:event_btn_salirActionPerformed

         private void txt_buscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyTyped
                  // TODO add your handling code here:

                  int pos = txt_buscar.getCaretPosition();
                  String parametro = (txt_buscar.getText().substring(0, pos) + evt.getKeyChar() + txt_buscar.getText().substring(pos)).trim();

                  if (parametro.trim().length() == 0) {
                           control.fillTable2(tabla, " select * from v_alumnos");
                  } else {

                           String sql = "select * from v_alumnos where dni like '%" + parametro + "%' or nombre like '%" + parametro + "%' or apellido like '%" + parametro + "%' or correo like '%" + parametro + "%' or codigo like '%" + parametro + "%'";
                           control.fillTable2(tabla, sql);

                  }

         }//GEN-LAST:event_txt_buscarKeyTyped

         private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                  // TODO add your handling code here:
                  //  control.reporteEstatico("src\\reportes\\alumnos.jasper");
                  HashMap parametros = new HashMap<>();
                  JasperViewer reporte = control.showReport("reportes/alumnos.jasper", parametros);
                  try {
                           reporte.setTitle("mostrando todo los alumnos ");
                  } catch (Exception e) {
                  }


         }//GEN-LAST:event_jButton1ActionPerformed

         /**
          * @param args the command line arguments
          */
         public static void main(String args[]) {
                  /* Set the Nimbus look and feel */
                  //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                  /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                   */
                  try {
                           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                    if ("Nimbus".equals(info.getName())) {
                                             javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                             break;
                                    }
                           }
                  } catch (ClassNotFoundException ex) {
                           java.util.logging.Logger.getLogger(alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  } catch (InstantiationException ex) {
                           java.util.logging.Logger.getLogger(alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  } catch (IllegalAccessException ex) {
                           java.util.logging.Logger.getLogger(alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                           java.util.logging.Logger.getLogger(alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  }
                  //</editor-fold>

                  /* Create and display the dialog */
                  java.awt.EventQueue.invokeLater(new Runnable() {
                           public void run() {
                                    alumno dialog = new alumno(new javax.swing.JFrame(), false);
                                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                                             @Override
                                             public void windowClosing(java.awt.event.WindowEvent e) {
                                                      System.exit(0);
                                             }
                                    });
                                    dialog.setVisible(true);
                           }
                  });
         }

         // Variables declaration - do not modify//GEN-BEGIN:variables
         private javax.swing.JButton btn_actualizar;
         private javax.swing.JButton btn_cancelar;
         private javax.swing.JButton btn_crear;
         private javax.swing.JButton btn_eliminar;
         private javax.swing.JButton btn_salir;
         private javax.swing.JComboBox<String> cb_escuela;
         private javax.swing.JComboBox<String> cb_gen;
         private javax.swing.JButton jButton1;
         private javax.swing.JLabel jLabel1;
         private javax.swing.JLabel jLabel10;
         private javax.swing.JLabel jLabel2;
         private javax.swing.JLabel jLabel3;
         private javax.swing.JLabel jLabel4;
         private javax.swing.JLabel jLabel5;
         private javax.swing.JLabel jLabel6;
         private javax.swing.JLabel jLabel7;
         private javax.swing.JLabel jLabel8;
         private javax.swing.JLabel jLabel9;
         private javax.swing.JPanel jPanel1;
         private javax.swing.JPanel jPanel2;
         private javax.swing.JScrollPane jScrollPane1;
         private javax.swing.JSeparator jSeparator1;
         private javax.swing.JTable tabla;
         private javax.swing.JTextField txt_apell;
         private javax.swing.JTextField txt_buscar;
         private javax.swing.JTextField txt_celular;
         private javax.swing.JTextField txt_cod;
         private javax.swing.JTextField txt_correo;
         private javax.swing.JTextField txt_dir;
         private javax.swing.JTextField txt_dni;
         private javax.swing.JTextField txt_nom;
         // End of variables declaration//GEN-END:variables
}
