/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.control;
import clases.validar;
import com.mysql.cj.protocol.Resultset;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class entregas extends javax.swing.JDialog {
         int usuario_id=3;
         DefaultListModel modelo = new DefaultListModel();

         /**
          * Creates new form entregas
          */
         public entregas(java.awt.Frame parent, boolean modal) {
                  super(parent, modal);
                  initComponents();
                  lista.setModel(modelo);
                  setLocationRelativeTo(null);
         }
         
           public entregas(java.awt.Frame parent, boolean modal,int usuario_id) {
                  super(parent, modal);
                  this.usuario_id=usuario_id;
                  initComponents();
                  lista.setModel(modelo);
                  setLocationRelativeTo(null);
         }

         private void limpiar() {
                  modelo.removeAllElements();
                  cb_equipo.removeAllItems();
                  txt_buscar.setText("");
                  lb_resultado.setText("");
         }

         /**
          * This method is called from within the constructor to
          * initialize the form. WARNING: Do NOT modify this code. The
          * content of this method is always regenerated by the Form
          * Editor.
          */
         @SuppressWarnings("unchecked")
         // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
         private void initComponents() {

                  jPanel1 = new javax.swing.JPanel();
                  jLabel1 = new javax.swing.JLabel();
                  txt_buscar = new javax.swing.JTextField();
                  lb_resultado = new javax.swing.JLabel();
                  jPanel2 = new javax.swing.JPanel();
                  jLabel3 = new javax.swing.JLabel();
                  cb_equipo = new javax.swing.JComboBox<>();
                  jScrollPane1 = new javax.swing.JScrollPane();
                  lista = new javax.swing.JList<>();
                  bt_grabar = new javax.swing.JButton();
                  bt_cancelar = new javax.swing.JButton();
                  bt_salir = new javax.swing.JButton();

                  setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                  jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("buscar alumno"));

                  jLabel1.setText("identificación : ");

                  txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
                           public void keyTyped(java.awt.event.KeyEvent evt) {
                                    txt_buscarKeyTyped(evt);
                           }
                  });

                  lb_resultado.setText("no hay ningun dato");

                  javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                  jPanel1.setLayout(jPanel1Layout);
                  jPanel1Layout.setHorizontalGroup(
                           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel1)
                                    .addGap(29, 29, 29)
                                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lb_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap(142, Short.MAX_VALUE))
                  );
                  jPanel1Layout.setVerticalGroup(
                           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(36, 36, 36)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                             .addComponent(jLabel1)
                                             .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addComponent(lb_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addContainerGap(47, Short.MAX_VALUE))
                  );

                  jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("entregas"));

                  jLabel3.setText("equipo");

                  cb_equipo.addItemListener(new java.awt.event.ItemListener() {
                           public void itemStateChanged(java.awt.event.ItemEvent evt) {
                                    cb_equipoItemStateChanged(evt);
                           }
                  });
                  cb_equipo.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    cb_equipoActionPerformed(evt);
                           }
                  });

                  jScrollPane1.setViewportView(lista);

                  bt_grabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar-el-archivo.png"))); // NOI18N
                  bt_grabar.setText("grabar entrega");
                  bt_grabar.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    bt_grabarActionPerformed(evt);
                           }
                  });

                  bt_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incorrecto.png"))); // NOI18N
                  bt_cancelar.setText("cancelar");
                  bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    bt_cancelarActionPerformed(evt);
                           }
                  });

                  bt_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hogar.png"))); // NOI18N
                  bt_salir.setText("finalizar");
                  bt_salir.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    bt_salirActionPerformed(evt);
                           }
                  });

                  javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                  jPanel2.setLayout(jPanel2Layout);
                  jPanel2Layout.setHorizontalGroup(
                           jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addComponent(jLabel3)
                                    .addGap(26, 26, 26)
                                    .addComponent(cb_equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(bt_grabar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(bt_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(bt_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap(104, Short.MAX_VALUE))
                  );
                  jPanel2Layout.setVerticalGroup(
                           jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addContainerGap(21, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18))
                           .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(61, 61, 61)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                      .addComponent(jLabel3)
                                                      .addComponent(cb_equipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                             .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                      .addComponent(bt_grabar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addComponent(bt_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addComponent(bt_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                  );

                  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                  getContentPane().setLayout(layout);
                  layout.setHorizontalGroup(
                           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(layout.createSequentialGroup()
                                    .addGap(43, 43, 43)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                             .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                             .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                  );
                  layout.setVerticalGroup(
                           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(layout.createSequentialGroup()
                                    .addGap(57, 57, 57)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap(95, Short.MAX_VALUE))
                  );

                  pack();
         }// </editor-fold>//GEN-END:initComponents

         private void cb_equipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_equipoActionPerformed
                  // TODO add your handling code here:
                  if (cb_equipo.getSelectedIndex() > -1) {

                           if (!validar.BuscarDatoenJList(modelo, cb_equipo.getSelectedItem().toString())) {
                                    modelo.addElement(cb_equipo.getSelectedItem().toString());
                           }

                  }

         }//GEN-LAST:event_cb_equipoActionPerformed

         private void txt_buscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyTyped
                  // TODO add your handling code here:
                  if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
                           cb_equipo.removeAllItems();
                           String buscar = txt_buscar.getText().trim();
                           try {
                                    String sql = String.format("select * from v_alumnos where codigo='%s' or dni='%s'", buscar, buscar);
                                    if (control.checkQuery(sql)) {
                                             sql = String.format("select count(*) from v_detalle_entrega where codigo='%s' or dni='%s'", buscar, buscar);
                                             int cant = Integer.parseInt(control.returnData(sql));

                                             switch (cant) {

                                                      case 0:
                                                               sql = String.format("select codigo, nombre,apellido, escuela from v_alumnos where codigo='%s' or dni='%s'", buscar, buscar);

                                                               ResultSet resultSet = control.returnResultset(sql);
                                                               if (resultSet.next()) {
                                                                        String mensaje = String.format("alumno: %s, %s %s, %s", resultSet.getString(1), resultSet.getString(2), resultSet.getString(3),
                                                                                resultSet.getString(4));
                                                                        lb_resultado.setText(mensaje);

                                                                        cb_equipo.addItem("LAPTOP");

                                                                        cb_equipo.addItem("CHIP DE DATOS");

                                                               }

                                                               break;
                                                      case 1:
                                                               sql = String.format("select codigo,nombre,apellido,escuela,tipo from v_detalle_entrega where codigo ='%s' or dni='%s'", buscar, buscar);

                                                               resultSet = control.returnResultset(sql);
                                                               if (resultSet.next()) {
                                                                        String mensaje = String.format("alumno: %s, %s %s, %s", resultSet.getString(1), resultSet.getString(2), resultSet.getString(3),
                                                                                resultSet.getString(4));
                                                                        lb_resultado.setText(mensaje);

                                                                        if (resultSet.getString(5).equalsIgnoreCase("CHIP DE DATOS")) {
                                                                                 cb_equipo.addItem("LAPTOP");
                                                                        } else if (resultSet.getString(5).equalsIgnoreCase("LAPTOP")) {
                                                                                 cb_equipo.addItem("CHIP DE DATOS");
                                                                        }

                                                               }

                                                               break;
                                                      case 2:
                                                               lb_resultado.setText("");

                                                               JOptionPane.showMessageDialog(txt_buscar, " al alumno ya recibió ambos equipos");

                                                               break;

                                             }
                                             cb_equipo.setSelectedIndex(-1);
                                             modelo.removeAllElements();
                                    } else {
                                             lb_resultado.setText("no hay datos");
                                             JOptionPane.showMessageDialog(txt_buscar, "el alumno no se encuentra registrado");

                                    }
                           } catch (SQLException ex) {
                                    Logger.getLogger(entregas.class.getName()).log(Level.SEVERE, null, ex);
                           }
                  }
         }//GEN-LAST:event_txt_buscarKeyTyped

         private void cb_equipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_equipoItemStateChanged
                  // TODO add your handling code here:


         }//GEN-LAST:event_cb_equipoItemStateChanged

         private void bt_grabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_grabarActionPerformed
                  // TODO add your handling code here:

                  if (modelo.getSize() == 1) {
                           String sql = String.format("select id from v_alumnos where dni='%s' or codigo='%s'", txt_buscar.getText().trim(), txt_buscar.getText().trim());
                           int alumno_id = Integer.parseInt(control.returnData(sql));
                           sql = String.format("insert into entrega values(null,curdate(),curtime(),%s,%s)", alumno_id,usuario_id);
                           int resp = control.update(sql);

                           int entrega_id = Integer.parseInt(control.returnData("select idEntrega from entrega order by idEntrega desc limit 1 "));

                           sql = String.format("insert into detalleentrega values(null,'%s','desconocido',%s)", modelo.getElementAt(0), entrega_id);
                           int resp2 = control.update(sql);
                           if (resp > 0 && resp2 > 0) {
                                    JOptionPane.showMessageDialog(bt_grabar, "se grabó correctamente");
                           }
                          limpiar();

                  } else if (modelo.getSize() == 2) {
                           String sql = String.format("select id from v_alumnos where dni='%s' or codigo='%s'", txt_buscar.getText().trim(), txt_buscar.getText().trim());
                           int alumno_id = Integer.parseInt(control.returnData(sql));

                           sql = String.format("insert into entrega values(null,curdate(),curtime(),%s,%s)", alumno_id,usuario_id);
                           int resp = control.update(sql);

                           int entrega_id = Integer.parseInt(control.returnData("select idEntrega from entrega order by idEntrega desc limit 1 "));

                           sql = String.format("insert into detalleentrega values(null, '%s','deconocido',%s),(null,'%s','desconocido',%s)",
                                   modelo.getElementAt(0), entrega_id, modelo.getElementAt(1), entrega_id);

                           int resp2 = control.update(sql);
                           if (resp > 0 && resp2 > 0) {
                                    JOptionPane.showMessageDialog(bt_grabar, "se grabó correctamente");
                           }
                         limpiar();
                  } else {
                           JOptionPane.showMessageDialog(bt_grabar, "no hay nada que grabar");
                  }
         }//GEN-LAST:event_bt_grabarActionPerformed

         private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
                  // TODO add your handling code here:
              limpiar();
         }//GEN-LAST:event_bt_cancelarActionPerformed

         private void bt_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salirActionPerformed
                  // TODO add your handling code here:
                  if (JOptionPane.showConfirmDialog(bt_salir, "¿desea volver a la ventana  principal?") == 0) {
                           dispose();
                  }
         }//GEN-LAST:event_bt_salirActionPerformed

         /**
          * @param args the command line arguments
          */
         public static void main(String args[]) {
                  /* Set the Nimbus look and feel */
                  //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                  /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                   */
                  try {
                           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                    if ("Nimbus".equals(info.getName())) {
                                             javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                             break;
                                    }
                           }
                  } catch (ClassNotFoundException ex) {
                           java.util.logging.Logger.getLogger(entregas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  } catch (InstantiationException ex) {
                           java.util.logging.Logger.getLogger(entregas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  } catch (IllegalAccessException ex) {
                           java.util.logging.Logger.getLogger(entregas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                           java.util.logging.Logger.getLogger(entregas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  }
                  //</editor-fold>

                  /* Create and display the dialog */
                  java.awt.EventQueue.invokeLater(new Runnable() {
                           public void run() {
                                    entregas dialog = new entregas(new javax.swing.JFrame(), true);
                                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                                             @Override
                                             public void windowClosing(java.awt.event.WindowEvent e) {
                                                      System.exit(0);
                                             }
                                    });
                                    dialog.setVisible(true);
                           }
                  });
         }

         // Variables declaration - do not modify//GEN-BEGIN:variables
         private javax.swing.JButton bt_cancelar;
         private javax.swing.JButton bt_grabar;
         private javax.swing.JButton bt_salir;
         private javax.swing.JComboBox<String> cb_equipo;
         private javax.swing.JLabel jLabel1;
         private javax.swing.JLabel jLabel3;
         private javax.swing.JPanel jPanel1;
         private javax.swing.JPanel jPanel2;
         private javax.swing.JScrollPane jScrollPane1;
         private javax.swing.JLabel lb_resultado;
         private javax.swing.JList<String> lista;
         private javax.swing.JTextField txt_buscar;
         // End of variables declaration//GEN-END:variables
}
