/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.control;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.HashMap;
import javax.swing.ImageIcon;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class principal extends javax.swing.JFrame {

         int usuario_id = 3;

         /**
          * Creates new form principal
          */
         public principal() {
                  initComponents();
                  setLocationRelativeTo(null);
                  setTitle("programa principal");
         }

         public principal(String usuario_id) {
                  initComponents();
                  this.usuario_id = Integer.parseInt(usuario_id);
                  setLocationRelativeTo(null);
                  setTitle("programa principal");
                  String usuario = control.returnData("select login from usuario where idUsuario=" + this.usuario_id);
                  jLabel1.setText(usuario + ", te damos la coordial bienvenida!");
         }

         /**
          * This method is called from within the constructor to
          * initialize the form. WARNING: Do NOT modify this code. The
          * content of this method is always regenerated by the Form
          * Editor.
          */
         @SuppressWarnings("unchecked")
         // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
         private void initComponents() {

                  jLabel1 = new javax.swing.JLabel();
                  jLabel2 = new javax.swing.JLabel();
                  jLabel3 = new javax.swing.JLabel();
                  jMenuBar1 = new javax.swing.JMenuBar();
                  jMenu1 = new javax.swing.JMenu();
                  jMenuItem1 = new javax.swing.JMenuItem();
                  jMenuItem2 = new javax.swing.JMenuItem();
                  jMenuItem3 = new javax.swing.JMenuItem();
                  jMenuItem4 = new javax.swing.JMenuItem();
                  jMenu2 = new javax.swing.JMenu();
                  jMenuItem5 = new javax.swing.JMenuItem();
                  jMenu3 = new javax.swing.JMenu();
                  jMenuItem6 = new javax.swing.JMenuItem();
                  jMenuItem7 = new javax.swing.JMenuItem();

                  setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                  jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
                  jLabel1.setForeground(new java.awt.Color(255, 255, 255));

                  jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/universidad.jpg"))); // NOI18N

                  jLabel3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                  jLabel3.setForeground(new java.awt.Color(255, 255, 255));
                  jLabel3.setText("SISTEMA DE ENTREGA DE CHIPS Y LAPTOP");

                  jMenu1.setForeground(new java.awt.Color(255, 255, 255));
                  jMenu1.setText("registros");

                  jMenuItem1.setForeground(new java.awt.Color(255, 255, 255));
                  jMenuItem1.setText("registrar faculades");
                  jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    jMenuItem1ActionPerformed(evt);
                           }
                  });
                  jMenu1.add(jMenuItem1);

                  jMenuItem2.setForeground(new java.awt.Color(255, 255, 255));
                  jMenuItem2.setText("registrar escuelas");
                  jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    jMenuItem2ActionPerformed(evt);
                           }
                  });
                  jMenu1.add(jMenuItem2);

                  jMenuItem3.setForeground(new java.awt.Color(255, 255, 255));
                  jMenuItem3.setText(" registrar alumnos");
                  jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    jMenuItem3ActionPerformed(evt);
                           }
                  });
                  jMenu1.add(jMenuItem3);

                  jMenuItem4.setForeground(new java.awt.Color(255, 255, 255));
                  jMenuItem4.setText("registrar administradores");
                  jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    jMenuItem4ActionPerformed(evt);
                           }
                  });
                  jMenu1.add(jMenuItem4);

                  jMenuBar1.add(jMenu1);

                  jMenu2.setForeground(new java.awt.Color(255, 255, 255));
                  jMenu2.setText("entregas");

                  jMenuItem5.setForeground(new java.awt.Color(255, 255, 255));
                  jMenuItem5.setText("entregar materiales");
                  jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    jMenuItem5ActionPerformed(evt);
                           }
                  });
                  jMenu2.add(jMenuItem5);

                  jMenuBar1.add(jMenu2);

                  jMenu3.setForeground(new java.awt.Color(255, 255, 255));
                  jMenu3.setText("reportes");

                  jMenuItem6.setForeground(new java.awt.Color(255, 255, 255));
                  jMenuItem6.setText("reporte de entregas");
                  jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    jMenuItem6ActionPerformed(evt);
                           }
                  });
                  jMenu3.add(jMenuItem6);

                  jMenuItem7.setForeground(new java.awt.Color(255, 255, 255));
                  jMenuItem7.setText("reporte de alumnos que faltan entregar");
                  jMenu3.add(jMenuItem7);

                  jMenuBar1.add(jMenu3);

                  setJMenuBar(jMenuBar1);

                  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                  getContentPane().setLayout(layout);
                  layout.setHorizontalGroup(
                           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                           .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addGroup(layout.createSequentialGroup()
                                                      .addGap(173, 173, 173)
                                                      .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1057, javax.swing.GroupLayout.PREFERRED_SIZE))
                                             .addGroup(layout.createSequentialGroup()
                                                      .addGap(358, 358, 358)
                                                      .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addContainerGap(180, Short.MAX_VALUE))
                  );
                  layout.setVerticalGroup(
                           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(layout.createSequentialGroup()
                                    .addGap(35, 35, 35)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(58, 58, 58)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                  );

                  pack();
         }// </editor-fold>//GEN-END:initComponents

         private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
                  // TODO add your handling code here:
                  (new escuela(this, false)).setVisible(true);
         }//GEN-LAST:event_jMenuItem2ActionPerformed

         private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
                  // TODO add your handling code here:
                  (new alumno(this, false)).setVisible(true);
         }//GEN-LAST:event_jMenuItem3ActionPerformed

         private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
                  // TODO add your handling code here:
         }//GEN-LAST:event_jMenuItem4ActionPerformed

         private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
                  // TODO add your handling code here:
                  (new facultades(this, false)).setVisible(true);
         }//GEN-LAST:event_jMenuItem1ActionPerformed

         private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
                  // TODO add your handling code here:

                  (new entregas(this, false, usuario_id)).setVisible(true);
         }//GEN-LAST:event_jMenuItem5ActionPerformed

         private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
                  // TODO add your handling code here:

                  HashMap parametros = new HashMap<>();
                  JasperViewer reporte = control.showReport("reportes/entregas.jasper", parametros);
                  try {
                           reporte.setTitle("mostrando los detalles de las entregas");
                  } catch (Exception e) {
                  }
         }//GEN-LAST:event_jMenuItem6ActionPerformed

         /**
          * @param args the command line arguments
          */
         public static void main(String args[]) {
                  /* Set the Nimbus look and feel */
                  //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                  /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                   */
                  try {
                           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                    if ("Nimbus".equals(info.getName())) {
                                             javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                             break;
                                    }
                           }
                  } catch (ClassNotFoundException ex) {
                           java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  } catch (InstantiationException ex) {
                           java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  } catch (IllegalAccessException ex) {
                           java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                           java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                  }
                  //</editor-fold>

                  /* Create and display the form */
                  java.awt.EventQueue.invokeLater(new Runnable() {
                           public void run() {
                                    new principal().setVisible(true);
                           }
                  });
         }

         // Variables declaration - do not modify//GEN-BEGIN:variables
         private javax.swing.JLabel jLabel1;
         private javax.swing.JLabel jLabel2;
         private javax.swing.JLabel jLabel3;
         private javax.swing.JMenu jMenu1;
         private javax.swing.JMenu jMenu2;
         private javax.swing.JMenu jMenu3;
         private javax.swing.JMenuBar jMenuBar1;
         private javax.swing.JMenuItem jMenuItem1;
         private javax.swing.JMenuItem jMenuItem2;
         private javax.swing.JMenuItem jMenuItem3;
         private javax.swing.JMenuItem jMenuItem4;
         private javax.swing.JMenuItem jMenuItem5;
         private javax.swing.JMenuItem jMenuItem6;
         private javax.swing.JMenuItem jMenuItem7;
         // End of variables declaration//GEN-END:variables
}
