/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
 */
import javax.swing.ImageIcon;
import Clases.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ing. Miguel Angel Silva Zapata
 */
public class Entregas extends javax.swing.JInternalFrame {

         control control = new control();
         DefaultListModel ltmd = new DefaultListModel();

         /**
          * Creates new form Entregas
          */
         public Entregas() {
                  initComponents();
                  setTitle("Entrega de Equipos");
                  setFrameIcon(new ImageIcon(this.getClass().getResource("/Imagenes/icoChiqui.png")));
                  lbResultado.setText("");
                  Equiposxentregar.setModel(ltmd);
                  cbEquipo.addActionListener(new ActionListener() {
                           @Override
                           public void actionPerformed(ActionEvent e) {
                                    Agregar();
                           }
                  });
         }

         public void Agregar() {
                  if (cbEquipo.getSelectedIndex() > -1) {
                           if (!control.BuscarDatoenJList(ltmd, cbEquipo.getSelectedItem().toString())) {
                                    ltmd.addElement(cbEquipo.getSelectedItem().toString());
                           } else {
                                    JOptionPane.showMessageDialog(null, cbEquipo.getSelectedItem().toString() + " Ya esta agregado");
                           }
                  }
                  cbEquipo.setSelectedIndex(-1);
         }

         public void Buscar() {
                  int catd = Integer.parseInt(control.returnData("select count(*) from entrega where "
                          + "idalumnovulnerable in(select idalumnovulnerable from vtaalumnos where dni"
                          + "='" + txBuscar.getText() + "' or codigo='" + txBuscar.getText() + "');"));
                  if (catd > 0) {
                           switch (catd) {
                                    case 1: {
                                             int cad = Integer.parseInt(control.DevolverRegistroDto("select count(*) from "
                                                     + "detalleentrega where identrega=(select identrega from entrega where idalumnovulnerable"
                                                     + " in(select idalumnovulnerable from vtaalumnos where dni='" + txBuscar.getText()
                                                     + "' or codigo='" + txBuscar.getText() + "'));", 1));
                                             if (cad == 2) {
                                                      JOptionPane.showMessageDialog(null, "El Alumno ya recibio sus dos dispositivos en una");
                                             } else {
                                                      control.Base.rt = control.DevolverRegistro("select * from "
                                                              + "vtaalumnos where dni='" + txBuscar.getText() + "' or codigo='" + txBuscar.getText() + "'");
                                                      try {
                                                               if (control.Base.rt.next()) {
                                                                        lbResultado.setText("Alumno: " + control.Base.rt.getString(2) + ", " + control.Base.rt.getString(4)
                                                                                + ", " + control.Base.rt.getString(8));
                                                               }
                                                      } catch (Exception e) {
                                                      }
                                             }
                                             break;
                                    }
                                    case 2: {
                                             JOptionPane.showMessageDialog(null, "El Alumno ya recibio sus dos dispositivos en dos");
                                             break;
                                    }
                           }
                  } else {
                           lbResultado.setText("");
                  }
         }

         /**
          * This method is called from within the constructor to
          * initialize the form. WARNING: Do NOT modify this code. The
          * content of this method is always regenerated by the Form
          * Editor.
          */
         @SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">
         private void initComponents() {

                  jPanel1 = new javax.swing.JPanel();
                  lbResultado = new javax.swing.JLabel();
                  txBuscar = new javax.swing.JTextField();
                  jLabel2 = new javax.swing.JLabel();
                  jPanel2 = new javax.swing.JPanel();
                  jLabel3 = new javax.swing.JLabel();
                  cbEquipo = new javax.swing.JComboBox<>();
                  jScrollPane1 = new javax.swing.JScrollPane();
                  Equiposxentregar = new javax.swing.JList<>();
                  btSalir = new javax.swing.JButton();
                  btGrabar = new javax.swing.JButton();
                  btCancelar = new javax.swing.JButton();

                  getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                  jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Alumno", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
                  jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                  lbResultado.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
                  lbResultado.setText("Al");
                  jPanel1.add(lbResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 25, 570, -1));

                  txBuscar.setToolTipText("Despues de ingresar el Dni o el Código, Presione Enter...");
                  txBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
                           public void keyReleased(java.awt.event.KeyEvent evt) {
                                    txBuscarKeyReleased(evt);
                           }

                           public void keyTyped(java.awt.event.KeyEvent evt) {
                                    txBuscarKeyTyped(evt);
                           }
                  });
                  jPanel1.add(txBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 22, 110, -1));

                  jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
                  jLabel2.setText("Identificación:");
                  jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, -1, -1));

                  getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 60));

                  jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Entrega", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
                  jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                  jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
                  jLabel3.setText("Equipo");
                  jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

                  cbEquipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Laptop", "Chip de Datos"}));
                  cbEquipo.setSelectedIndex(-1);
                  jPanel2.add(cbEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 44, 160, -1));

                  jScrollPane1.setViewportView(Equiposxentregar);

                  jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 120, 80));

                  btSalir.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
                  btSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
                  btSalir.setMnemonic('s');
                  btSalir.setText("Salir");
                  btSalir.addActionListener(new java.awt.event.ActionListener() {
                           public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    btSalirActionPerformed(evt);
                           }
                  });
                  jPanel2.add(btSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, 100, 40));

                  btGrabar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
                  btGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save.png"))); // NOI18N
                  btGrabar.setMnemonic('g');
                  btGrabar.setText("Grabar");
                  jPanel2.add(btGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 100, 40));

                  btCancelar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
                  btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel.png"))); // NOI18N
                  btCancelar.setMnemonic('c');
                  btCancelar.setText("Cancelar");
                  btCancelar.setMargin(new java.awt.Insets(2, 1, 2, 14));
                  jPanel2.add(btCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 100, 40));

                  getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 810, 110));

                  pack();
         }// </editor-fold>

         private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {
                  dispose();
         }

         private void txBuscarKeyTyped(java.awt.event.KeyEvent evt) {
         }

         private void txBuscarKeyReleased(java.awt.event.KeyEvent evt) {
                  Buscar();
         }

// Variables declaration - do not modify
         private javax.swing.JList<String> Equiposxentregar;
         private javax.swing.JButton btCancelar;
         private javax.swing.JButton btGrabar;
         private javax.swing.JButton btSalir;
         private javax.swing.JComboBox<String> cbEquipo;
         private javax.swing.JLabel jLabel2;
         private javax.swing.JLabel jLabel3;
         private javax.swing.JPanel jPanel1;
         private javax.swing.JPanel jPanel2;
         private javax.swing.JScrollPane jScrollPane1;
         private javax.swing.JLabel lbResultado;
         private javax.swing.JTextField txBuscar;
// End of variables declaration
}
